language: python
python: 2.7
install:
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg --version 2.2.5 --setuptools-version 7.0
    - bin/buildout -N -t 3 -c travis.cfg --version 2.2.5 --setuptools-version 7.0
script: bin/test
